### PR TITLE
support Ruby 2.4's frozen string literals (1.4.x branch)

### PR DESCRIPTION
**Pull request by flavorjones**
Note this change is made relative to the 1-4-stable branch.

It would be great to cut an updated 1.4.x release after merging this in.

### CODE REVIEW

**Comment by flavorjones** [comment]
Note that you can test before/after by setting `RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal"`

**Comment by drbrain** [comment]
Will an `eval` test work?

**Comment by flavorjones** [comment]
@drbrain Not sure what you mean?

**Comment by drbrain** [comment]
A test like:

```ruby
parser_output = Racc.generate_a_parser "grammar"

eval "# frozen_string_literal: true\n#{parser_output}"

Parser.parse "something"

assert true, "Parser didn't raise a frozen string exception, 🎊"
```

**Comment by flavorjones** [comment]
Ah, I see what you're getting at.

For the 1.4 branch, this changeset was small, but check out what had to be done for master: #81 

So I'd personally prefer to see the entire test suite run with the frozen strings option; unfortunately the travis setup is outdated and has been failing for some time. I'll add a commit fixing it up, and you can be the judge.

**Comment by drbrain** [comment]
👍🏻

**Comment by pat** [comment]
I realise this PR has been dormant for quite some time. Would love to get frozen string literal support in though!

With regards to getting things on Travis green: I've just done some poking around, and added the following to try to get the tests running. They're actually running on 1.9 (albeit with some failures), but no luck elsewhere (due to minitest/autorun not being available for some reason): https://github.com/flavorjones/racc/compare/flavorjones-1.4-frozen-string-literal...pat:flavorjones-1.4-frozen-string-literal - the results can be found at https://travis-ci.org/pat/racc - any thoughts on next steps are very welcome :)

**Comment by hsbt** [comment]
@flavorjones Can you rebase with the current `1-4-stable` branch?

**Comment by flavorjones** [comment]
Rebased and pushed! Please take a look at my edit to the github actions, I'm not 100% sure what I'm doing there.

**Comment by flavorjones** [comment]
Re-pushed with an updated change to `lib/racc/parserfilegenerator.rb` to address frozen string test failures.

**Comment by flavorjones** [comment]
@hsbt - can you help me understand why this was closed without merging? I rebased as you requested and tests were green.

**Comment by hsbt** [comment]
@flavorjones Ah, I renamed `1-4-stable` to `master` branch. Can you submit this pull-request from master branch again?

**Comment by flavorjones** [comment]
@hsbt resubmitted as #127 rebased on master

**Pull request closed without merging**
