### PR TITLE
require jruby explicitly

### PR DESCRIPTION
**Pull request by ahorek**
fixes https://github.com/jruby/jruby/issues/6125

related to https://github.com/jruby/jruby/pull/5381

### CODE REVIEW

**Comment by hsbt** [comment]
@headius Can you review this?

**Comment by benoittgt** [comment]
We have now another error. Is this related? 

```
An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error:
  ControllerAssertionDelegator = RSpec::Rails::AssertionDelegator.new(
    ActionDispatch::Assertions::RoutingAssertions
  )

LoadError:
  no such file to load -- racc/info
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/nokogiri-1.9.1-java/lib/nokogiri/css/parser.rb:7:in `<main>'
```

https://travis-ci.org/github/rspec/rspec-rails/jobs/665433957?utm_medium=notification&utm_source=github_status

**Comment by headius** [comment]
> Is this related?

JRuby previously only shipped the extension and `parser.rb` because the rest of the source was licensed under something GPL-ish. That license has changed and `parser.rb` expects the rest of the gem to be present. I've fixed this by committing the rest of the racc library files for #6125.

We would prefer to source those files from the gem, but that will require @hsbt or someone else responsible for the racc gem to do a release.

**Comment by hsbt** [comment]
@headius I'm going to release the current master branch as racc-1.5.0 after cleaning-up the some of obsoleted files.

**Comment by hsbt** [comment]
@headius Done. https://github.com/ruby/racc/releases/tag/v1.5.0 and https://rubygems.org/gems/racc

**Comment by headius** [comment]
@hsbt Missed this until now. Thank you!

**Pull request merged**
