### PR TITLE
align table value

### PR DESCRIPTION
**Pull request by windwiny**

### CODE REVIEW

**Comment by alexdowad** [comment]
What is your intention here? Please explain.

**Comment by drbrain** [comment]
It looks like this restores pretty-printed tables in the racc output.

**Comment by drbrain** [comment]
```
$ cat integer_list.rb 
def old name, table
  lines = table.inspect.split(/((?:\w+, ){15})/).reject { |s| s.empty? }
  "#{name} = #{lines.join "\n"}"
end

def new name, table
  s = table.map { |e| "%6s" % e.inspect }.each_slice(10).to_a
  lines = s[0..-2].map { |e| e.join(',')+',' } << s[-1].join(',')
  "#{name} = [\n#{lines.join("\n")} ]"
end

name = 'test'
table = 50.times.map { rand -500..500 }

puts 'old:'
puts old name, table
puts
puts 'new:'
puts new name, table

$ ruby integer_list.rb 
old:
test = [449, 98, -180, 252, -402, -491, -66, -422, -498, 217, 296, -177, -376, 487, -328, 81, -430, 188, -208, -213, -378, -27, 274, -35, 198, 500, -481, 37, 248, 320, -439, -63, 163, 132, 487, -497, 404, -331, 308, 418, -214, -25, -155, 383, -451, 100, -252, -117, -235, 499]

new:
test = [
   449,    98,  -180,   252,  -402,  -491,   -66,  -422,  -498,   217,
   296,  -177,  -376,   487,  -328,    81,  -430,   188,  -208,  -213,
  -378,   -27,   274,   -35,   198,   500,  -481,    37,   248,   320,
  -439,   -63,   163,   132,   487,  -497,   404,  -331,   308,   418,
  -214,   -25,  -155,   383,  -451,   100,  -252,  -117,  -235,   499 ]
```

**Comment by alexdowad** [comment]
@drbrain Thanks. Do you think this is preferable?

**Comment by drbrain** [comment]
I prefer pretty-printing, I vote merge.

**Comment by alexdowad** [comment]
OK. But @windwiny's previous PR should be merged first, so as not to break the regression tests.

**Comment by zenspider** [comment]
This is stale. Closing. Please open a new PR if you want to re-open this dialog.

**Pull request closed without merging**
